---

- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python
  roles:
    - setup
    - nginx
    - php
    - mariadb
    - ftp
    - wordpress
